[window]

opacity = 1.0

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[colors]
primary.background = "#000000"

[scrolling]
history = 10000
multiplier = 3


